/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.Reglas;
import Controller.Variables;
import Model.Regla;
import Model.Variable;
import java.awt.BorderLayout;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author MIRKO
 */
public class MainFrame extends javax.swing.JFrame {
    Variables variables;
    Reglas reglas;
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        variables = new Variables();
        reglas = new Reglas();
        VariablesPanelForm variableView = new VariablesPanelForm(this);
        this.mostrarJPanel(variableView );
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton_variables = new javax.swing.JButton();
        jButton_reglas = new javax.swing.JButton();
        jPanel_content = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        opcion_guardar = new javax.swing.JMenuItem();
        opcion_cargar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton_variables.setText("Variables");
        jButton_variables.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_variablesActionPerformed(evt);
            }
        });

        jButton_reglas.setText("Reglas");
        jButton_reglas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_reglasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_contentLayout = new javax.swing.GroupLayout(jPanel_content);
        jPanel_content.setLayout(jPanel_contentLayout);
        jPanel_contentLayout.setHorizontalGroup(
            jPanel_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 518, Short.MAX_VALUE)
        );
        jPanel_contentLayout.setVerticalGroup(
            jPanel_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jMenu1.setText("File");

        opcion_guardar.setText("Guardar");
        opcion_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcion_guardarActionPerformed(evt);
            }
        });
        jMenu1.add(opcion_guardar);

        opcion_cargar.setText("Cargar");
        opcion_cargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcion_cargarActionPerformed(evt);
            }
        });
        jMenu1.add(opcion_cargar);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton_variables, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_reglas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel_content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel_content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton_variables)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_reglas)
                .addContainerGap(242, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void opcion_cargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcion_cargarActionPerformed
        Cargar cargar = new Cargar(this, true);
        cargar.setVisible(true);
    }//GEN-LAST:event_opcion_cargarActionPerformed

    private void jButton_variablesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_variablesActionPerformed
        VariablesPanelForm variablesView = new VariablesPanelForm(this);
        this.mostrarJPanel(variablesView);
    }//GEN-LAST:event_jButton_variablesActionPerformed

    private void jButton_reglasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_reglasActionPerformed
        ReglasPanelForm reglasView = new ReglasPanelForm(this);
        this.mostrarJPanel(reglasView);
    }//GEN-LAST:event_jButton_reglasActionPerformed

    private void opcion_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcion_guardarActionPerformed
        Guardar guardar = new Guardar(this, true);
        guardar.setVisible(true);
    }//GEN-LAST:event_opcion_guardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }
    private void mostrarJPanel(JPanel jpanel){
        jpanel.setSize(this.jPanel_content.getWidth(), this.jPanel_content.getHeight());
        jpanel.setLocation(0, 0);
        
        this.jPanel_content.removeAll();
        this.jPanel_content.add(jpanel, BorderLayout.CENTER);
        this.jPanel_content.revalidate();
        this.jPanel_content.repaint();
    }
    public void guardar(String filename){
        util.Util.saveToFile(filename, variables.getVariables(), reglas.getReglas());
        System.out.println("archivo guardado");
    }
    public void cargar(String filename){
        HashMap<String, Object> data = util.Util.loadFromFile(filename);
        this.variables = new Variables((ArrayList<Variable>)data.get("variables"));
        this.reglas = new Reglas((ArrayList<Regla>)data.get("reglas"));
        VariablesPanelForm variableView = new VariablesPanelForm(this);
        this.mostrarJPanel(variableView);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_reglas;
    private javax.swing.JButton jButton_variables;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel_content;
    private javax.swing.JMenuItem opcion_cargar;
    private javax.swing.JMenuItem opcion_guardar;
    // End of variables declaration//GEN-END:variables
}
