/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import Controller.Variables;
import Model.Escalar;
import Model.Numerica;
import Model.Variable;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MIRKO
 */
public class VariablesPanelForm extends javax.swing.JPanel {
    JFrame parent;
    Variables variables;
    DefaultTableModel modelo_tabla;
    /**
     * Creates new form VariablesPanelForm
     */
    public VariablesPanelForm(JFrame parent) {
        initComponents();
        this.parent = parent;
        this.variables = ((MainFrame)parent).variables;
        
        cargarDatosTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        crear_variable = new javax.swing.JButton();
        editar_variable = new javax.swing.JButton();
        eliminar_variable = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla_variables = new javax.swing.JTable();

        setBackground(new java.awt.Color(204, 204, 204));

        crear_variable.setText("Nueva Variable");
        crear_variable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crear_variableActionPerformed(evt);
            }
        });

        editar_variable.setText("Editar");
        editar_variable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editar_variableActionPerformed(evt);
            }
        });

        eliminar_variable.setText("Eliminar");
        eliminar_variable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminar_variableActionPerformed(evt);
            }
        });

        jLabel2.setText("Variables creadas");

        tabla_variables.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre", "Descripcion", "Tipo", "Valores/restriccion"
            }
        ));
        tabla_variables.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabla_variablesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabla_variables);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(editar_variable)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(eliminar_variable))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2)
                        .addComponent(crear_variable)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(crear_variable)
                .addGap(12, 12, 12)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(editar_variable)
                    .addComponent(eliminar_variable))
                .addContainerGap(12, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void crear_variableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crear_variableActionPerformed
        CreateVariable crear_variable = new CreateVariable(this.parent, true, this);
        crear_variable.setVisible(true);
    }//GEN-LAST:event_crear_variableActionPerformed

    private void tabla_variablesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabla_variablesMouseClicked
        
    }//GEN-LAST:event_tabla_variablesMouseClicked

    private void eliminar_variableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminar_variableActionPerformed
        int index = this.tabla_variables.getSelectedRow();
        if(index == -1) return;
        
        Variable variable = this.variables.getVariable(index);
        boolean esUsado = ((MainFrame)parent).reglas.variableEsUsada(variable);
        if(esUsado){
            JOptionPane.showMessageDialog(null, "No se puede eliminar la variable, es usada en una regla");
            return;
        } 
        
        this.variables.removeVariable(variables.getVariables().get(index).getNombre());
        this.cargarDatosTabla();
    }//GEN-LAST:event_eliminar_variableActionPerformed

    private void editar_variableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editar_variableActionPerformed
        int index = this.tabla_variables.getSelectedRow();
        if(index == -1) return;
        
        Variable variable = this.variables.getVariable(index);
        boolean esUsado = ((MainFrame)parent).reglas.variableEsUsada(variable);
        if(esUsado){
            JOptionPane.showMessageDialog(null, "No se puede editar la variable, es usada en una regla");
            return;
        } 
        
        EditVariable editar = new EditVariable(this.parent, true, this, variable);
        editar.setVisible(true);
    }//GEN-LAST:event_editar_variableActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton crear_variable;
    private javax.swing.JButton editar_variable;
    private javax.swing.JButton eliminar_variable;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabla_variables;
    // End of variables declaration//GEN-END:variables

    public void cargarDatosTabla() {
        String[] columnas = {"Nombre", "Descripcion", "Tipos", "Valores/restriccion"};
        modelo_tabla = new DefaultTableModel();
        modelo_tabla.setColumnIdentifiers(columnas);
        this.tabla_variables.setModel(modelo_tabla);
        
        ArrayList<Variable> variables_cargar = this.variables.getVariables();
        for(Variable variable : variables_cargar){
            if(variable.getTipo() == 'E'){
                String[] data = {variable.getNombre(), variable.getDescripcion(), "Escalar", ((Escalar)variable).getConjuntoValores().toString()};
                this.modelo_tabla.addRow(data);
            }else{
                Numerica varnum = (Numerica)variable;
                String restriccion = "";
                if(varnum.isHasMaxIntervalo()) restriccion = "max: "+varnum.getMaxIntervalo();
                if(varnum.isHasMinIntervalo()) restriccion += ", min: "+varnum.getMinIntervalo();
                String[] data = {variable.getNombre(), variable.getDescripcion(), "Numerica", restriccion};
                this.modelo_tabla.addRow(data);
            }
        }
    }
}
